FROM ubuntu
MAINTAINER Marc DellaVolpe "marc.dellavolpe@gmail.com"

VOLUME /site

ENV DEBIAN_FRONTEND noninteractive

RUN useradd -ms /bin/bash knapsack

RUN apt-get update
RUN apt-get install -y python python-dev python-setuptools python-pip git libpq-dev

COPY requirements.txt /tmp
RUN pip install -r /tmp/requirements.txt
RUN rm /tmp/requirements.txt

RUN apt-get purge -y git
RUN apt-get autoremove -y

ENV HOME /site
ENV PYTHON_EGG_CACHE /tmp/python-eggs
WORKDIR /site

ENV PYTHONPATH=/site
CMD ["pserve", "--reload", "development.ini"]